<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2736" started-at="2017-09-15T03:55:10Z" finished-at="2017-09-15T03:55:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2736" started-at="2017-09-15T03:55:10Z" finished-at="2017-09-15T03:55:13Z">
      <class name="cn.test.framework.tests.InterfaceTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be]" name="beforeSuite" is-config="true" duration-ms="138" started-at="2017-09-15T11:55:10Z" finished-at="2017-09-15T11:55:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="FAIL" signature="test_image_rec(java.util.Map)[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be]" name="test_image_rec" duration-ms="1397" started-at="2017-09-15T11:55:10Z" data-provider="testImageRec" finished-at="2017-09-15T11:55:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{vehicle_license_main_engine_no=C443305, address=北京市崇文区安化北里1号长保大厦123, type=中国行驶证正本, url=/icr/recognize_vehicle_license_demo, image_name=3.jpg, vehicle_license_main_user_character=非营运, issue_date=2008-07-10, vehicle_license_main_model=丰田G1M7240VBNAV1, vehicle_license_main_register_date=2008-07-10, vehicle_license_main_vehicle_type=轿车, vehicle_license_main_plate_num=京MD3033, vehicle_license_main_vin=LVGBE40KX8G230406, vehicle_license_main_owner=长安责任保险股份有限公司}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ 期望值: 北京市崇文区安化北里1号长保大厦123 实际值: 北京市崇文区安化北里1号笋保大厦]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦123 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:83)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:36)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦123 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:94)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:33)
	... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_image_rec -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be]" name="afterMethod" is-config="true" duration-ms="141" started-at="2017-09-15T11:55:12Z" finished-at="2017-09-15T11:55:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_image_rec status=FAILURE method=InterfaceTest.test_image_rec(java.util.Map)[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="test_image_rec(java.util.Map)[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be]" name="test_image_rec" duration-ms="1043" started-at="2017-09-15T11:55:12Z" data-provider="testImageRec" finished-at="2017-09-15T11:55:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{vehicle_license_main_engine_no=C443305, address=北京市崇文区安化北里1号长保大厦, type=中国行驶证正本, url=/icr/recognize_vehicle_license_demo, image_name=3.jpg, vehicle_license_main_user_character=非营运, issue_date=2008-07-10, vehicle_license_main_model=丰田G1M7240VBNAV1, vehicle_license_main_register_date=2008-07-10, vehicle_license_main_vehicle_type=轿车, vehicle_license_main_plate_num=京MD3033, vehicle_license_main_vin=LVGBE40KX8G230406, vehicle_license_main_owner=长安责任保险股份有限公司}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ 期望值: 北京市崇文区安化北里1号长保大厦 实际值: 北京市崇文区安化北里1号笋保大厦]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:83)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:36)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:94)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:33)
	... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_image_rec -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be]" name="afterMethod" is-config="true" duration-ms="23" started-at="2017-09-15T11:55:13Z" finished-at="2017-09-15T11:55:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_image_rec status=FAILURE method=InterfaceTest.test_image_rec(java.util.Map)[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:cn.test.framework.tests.InterfaceTest@3943a2be]" name="afterSuite" is-config="true" duration-ms="32" started-at="2017-09-15T11:55:13Z" finished-at="2017-09-15T11:55:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- cn.test.framework.tests.InterfaceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
